### ISSUE TITLE
resource not injected in a large K8s cluster

### ISSUE THREAD

**Issue by pperiyasamy** [k8snetworkplumbingwg/network-resources-injector#101]
When we bringup a deployment which has 100 pod replicas, then some pods are not created because NRI doesn't inject required SRIOV VF resources into the pod. 
From troubleshooting NRI (of course logging has to be improved by writing pod info as well in the logs), it looks NRI takes around 15 secs (because of GC ?) to respond to admission request for the failed pod whereas it just look  around 5 secs for the working pods. is admission response ignored due to timeout ? it happens though webhook timeout set to 30 sec (default value?). 
After changing `failurePolicy` from `Ignore` to `Fail`, then all pods are injected with resources. Does Fail policy make any difference ? As per the documentation, it says it would cause pod admission to fail. isn't it ?
If `Fail` policy fixes the issue, then we would need to make `failurePolicy` as configurable parameter, currently it's [hardcoded](https://github.com/k8snetworkplumbingwg/network-resources-injector/blob/628f2982daf036a97ca759efd2a633bd287298ff/pkg/installer/installer.go#L134) to use `Ignore` policy.

**Comment by pperiyasamy** [comment]
The fix #103 with Fail policy seem to working fine, I think #102 and #103 are good to go in.
but still we need to figure out if retries happen upon web hook's timeout (not sure if it's done by helm itself), enable profiling for web hook to find out hot spots.

**Comment by JanScheurich** [comment]
@pperiyasamy: 5 seconds for successfully mutated pods seems already long. But 15 seconds is ages. What is going on there? Where does the NRI spend this time?

**Comment by pperiyasamy** [comment]
@JanScheurich Yes, your suspicion is correct. The retrieval of net-attach-def from k8 for every admission review request causes delay, could reproduce it with single deployment having 100 pod replicas. at times net-attach-def retrieval takes around 5-6 seconds. looks api server imposes rate limiter when requests goes beyond some rate, need to check on that.

can we make NRI to rely on local cache for net-attach-def ? The NRI can watch on net-attach-def events and update its local map, I think `map[string]map[string]string` would be sufficient, containing `namespace + "/" + network-name `as key and `Annotations map `as value.

@martinkennelly @zshi-redhat WDYT ?

**Comment by zshi-redhat** [comment]
> @JanScheurich Yes, your suspicion is correct. The retrieval of net-attach-def from k8 for every admission review request causes delay, could reproduce it with single deployment having 100 pod replicas. at times net-attach-def retrieval takes around 5-6 seconds. looks api server imposes rate limiter when requests goes beyond some rate, need to check on that.
> 
> can we make NRI to rely on local cache for net-attach-def ? The NRI can watch on net-attach-def events and update its local map, I think `map[string]map[string]string` would be sufficient, containing `namespace + "/" + network-name `as key and `Annotations map `as value.
> 
> @martinkennelly @zshi-redhat WDYT ?

I think it makes sense to use cache so that NRI won't query the net-attach-def for every pod creation.
The cached content looks good, since we only care about the net-attach-def annotation (which contains the resource name).

**Comment by JanScheurich** [comment]
+1 for caching the NAD annotations.

**Comment by pperiyasamy** [comment]
thanks all for the feedback, let me work on a PR for implementing a local cache.
