### ISSUE TITLE
NRI pod restart not handled 

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [k8snetworkplumbingwg/network-resources-injector#119]
NRI doesn't currently handle nri pod restarts, if for some reason nri pod gets killed and there are no other nri pods in the cluster, then nri pod(and other pods) would not be able to start as the service serving the nri webhook(which is the nri pod itself) is down(as webhook configuration is still present).

**Comment by zshi-redhat** [comment]
@VivekThrivikraman-est  Will it work for you if it uses deployment rather than pod to create NRI instances?
