### ISSUE TITLE
Release of Network resources injector

### ISSUE THREAD

**Issue by esiperu-est** [k8snetworkplumbingwg/network-resources-injector#126]
There are some good fixes since the last release (1.4). Can someone trigger a new release.

**Comment by adrianchiris** [comment]
@esiperu-est following todays community meeting, we are OK to do a release.

A question:
how are you deploying NRI ? is it using sriov-network-operator ?

**Comment by esiperu-est** [comment]
Thank you for looking at this quickly and .. 

we are deploying NRI as individual deployment.

**Comment by SchSeba** [comment]
https://github.com/k8snetworkplumbingwg/network-resources-injector/releases/tag/v1.5
