### ISSUE TITLE
CI lane is not able to finish the kind deployment

### ISSUE THREAD

**Issue by SchSeba** [k8snetworkplumbingwg/network-resources-injector#129]
```
error: taint "node-role.kubernetes.io/master:NoSchedule" not found
Error: Process completed with exit code 1.
```

https://github.com/k8snetworkplumbingwg/network-resources-injector/actions/runs/3424387347/jobs/5889930696

**Comment by Eoghan1232** [comment]
#137  should resolve this issue.

**Comment by SchSeba** [comment]
closed by https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/138
