### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by kashifest** [k8snetworkplumbingwg/network-resources-injector#156]
Its been 2 years since the [last release](https://github.com/k8snetworkplumbingwg/network-resources-injector/releases/tag/v1.5).  Any plans for new release?

**Comment by SchSeba** [comment]
Hi @kashifest,

we talk about it in the last community meeting and agree that we are going to have a new release for the sriov operator (this is part of that operator)

we have 3 critical bugs to fix before the release. you can see more info in the meeting notes
https://docs.google.com/document/d/1sJQMHbxZdeYJPgAWK1aSt6yzZ4K_8es7woVIrwinVwI/edit

**Comment by kashifest** [comment]
Thanks @SchSeba, looking forward to it.

**Comment by SchSeba** [comment]
Hi @kashifest the release is out
https://github.com/k8snetworkplumbingwg/network-resources-injector/releases/tag/v1.6.0

closing this issue
