### ISSUE TITLE
Downward API Injection: Multiple containers in pod don't work

### ISSUE THREAD

**Issue by Billy99** [k8snetworkplumbingwg/network-resources-injector#44]
If there multiple containers in a pod that need Downward API fields injected, it doesn't work. There is logic in code that only looks at `pod.Spec.Containers[0]`.

**Comment by pperiyasamy** [comment]
@Billy99 Can I work on a PR for injecting podnetinfo into multiple containers ? Please let me know.

**Comment by Billy99** [comment]
@pperiyasamy  Yes, I have not started and won't have time in the near term. While you are looking at logic to walk through the list of containers, may be easy to add logic to address #43 as well (but your call).

**Comment by pperiyasamy** [comment]
@Billy99 since PR #51 is merged now, can we close this issue ?

**Comment by Billy99** [comment]
@pperiyasamy Yes, tested and looks good.
