### ISSUE TITLE
'User Defined Injections' feature is missing access rights to configmap

### ISSUE THREAD

**Issue by MichalGuzieniuk** [k8snetworkplumbingwg/network-resources-injector#85]
**What happened?**
NRI is not able to read configmaps, and in result is not able to inject user defined resources into POD specification.

In logs I see such warning
`W0407 09:50:20.910817       1 main.go:189] Failed to get configmap for user-defined injections: configmaps "nri-user-defined-injections" is forbidden: User "system:serviceaccount:kube-system:network-resources-injector-sa" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

**What did you expect to happen?**
I expect that NRI is able to get configuration from configmaps

**Note**
I did small research on this topic and I think that the problem are permissions defined at
https://github.com/k8snetworkplumbingwg/network-resources-injector/blob/ad8f87007972068bca901a56fb43651262eb381a/deployments/auth.yaml#L72

when I add there configmaps to the resources list, injection feature starts to work as expected.

**Comment by martinkennelly** [comment]
@MichalGuzieniuk  Good stuff finding this. Can you produce a PR to fix this?

**Comment by MichalGuzieniuk** [comment]
Sure, I will provide a PR with fix.
