### ISSUE TITLE
create new release 

### ISSUE THREAD

**Issue by pperiyasamy** [k8snetworkplumbingwg/network-resources-injector#92]
Hi, Can we have a new release on the NRI ? My project team would like to have a new release with this [fix](https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/79).

**Comment by martinkennelly** [comment]
I think this is a good idea to add a minor release so v1.1. ok with you @zshi-redhat ?

**Comment by zshi-redhat** [comment]
> I think this is a good idea to add a minor release so v1.1. ok with you @zshi-redhat ?

+1, I was just looking at the history commits and yes, v1.1 makes sense to me.

**Comment by martinkennelly** [comment]
@pperiyasamy Done
