### ISSUE TITLE
Can Network-Resources-Injector(NRI) to be deployed as a deployment

### ISSUE THREAD

**Issue by harper1011** [k8snetworkplumbingwg/network-resources-injector#95]
This is more or less a question toward to NRI:

Currently, according to example from https://github.com/k8snetworkplumbingwg/network-resources-injector/blob/master/deployments/server.yaml, the NRI was deployed as a Pod in K8S cluster.
But in case the node which holding NRI pod got broken or run out of resource, then NIR pod will be deleted/evicted and won't be re-created.

So we would like to know whether NRI can be deployed as a deployment?
If so, is there any requirement for NRI release version?

@zshi-redhat

**Comment by zshi-redhat** [comment]
> So we would like to know whether NRI can be deployed as a deployment?

Yes, it can be deployed as a k8s deployment.

> If so, is there any requirement for NRI release version?

No particular requirement afaik, we use the NRI before it ever has been released in openshift.
Here is an example of how NRI is deployed in SR-IOV operator: https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/bindata/manifests/webhook/server.yaml

**Comment by harper1011** [comment]
Got it, and thanks for your quick answer.
